### ISSUE TITLE
Default Blizzard Objective Tracker no hidden

### ISSUE THREAD

**Issue by roweboy1974** [Aiue/AQT#11]
I don't see a way to hide the default objective tracker.

**Comment by Aiue** [comment]
Good catch, I forgot about that one myself, as I have it set to not autotrack quests. I'll look into having it fixed for next release.

**Comment by Aiue** [comment]
With this having been fixed, I'll be looking at fixing a few more minor things and releasing a minor update. Hopefully this evening.
