### ISSUE TITLE
Error with version 1.0.1

### ISSUE THREAD

**Issue by roweboy1974** [Aiue/AQT#16]
Getting the below error with version 1.0.1 when turning in quests:

Date: 2019-10-01 17:56:59
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AQT\GUI.lua line 170:
   AQTIcon:SetParent(): Cannot set a 'nil' parent for fonts or textures
Debug:
   (tail call): ?
   (tail call): ?
   [C]: SetParent()
   AQT\GUI.lua:170: ReleaseIcon()
   AQT\GUI.lua:147: Release()
   AQT\Core.lua:320: Untrack()
   AQT\Core.lua:290: Remove()
   AQT\Core.lua:409: ?()
   ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:119

**Comment by Aiue** [comment]
Already fixed in the repo, I'll make sure to tag a new release later tonight (as in, within a few hours).
