### ISSUE TITLE
 1.0.1-classic - invalid capture index - no other addons...

### ISSUE THREAD

**Issue by daberniegithub** [Aiue/AQT#17]
Message: Interface\AddOns\AQT\Core.lua:215: invalid capture index
Time: Wed Oct  2 06:21:30 2019
Count: 1
Stack: Interface\AddOns\AQT\Core.lua:215: invalid capture index
[C]: in function `match'
Interface\AddOns\AQT\Core.lua:215: in function `Update'
Interface\AddOns\AQT\Core.lua:366: in function `UpdateObjectives'
Interface\AddOns\AQT\Core.lua:352: in function `Update'
Interface\AddOns\AQT\Core.lua:284: in function `New'
Interface\AddOns\AQT\Core.lua:395: in function `?'
...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...erface\AddOns\AQT\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...erface\AddOns\AQT\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by Aiue** [comment]
Hmm. I've been unable to reproduce this myself. So I need a tiny bit of more information on the environment you're running on.

Which localization are you running on?
What's the return if you run `/script print(QUEST_ITEMS_NEEDED)`?

**Comment by Aiue** [comment]
Trying to look into it myself, but apparently changing language requires me to patch the game.

**Comment by Aiue** [comment]
Right. It seems the issue here is localization:

> QUEST_MONSTERS_KILLED
enGB: %s slain: %d/%d
deDE: %1$s getötet: %2$d/%3$d

>QUEST_ITEMS_NEEDED
enGB: %s: %d/%d
deDE: %1$s: %2$d/%3$d

>QUEST_OBJECTS_FOUND
enGB: %s: %d/%d
deDE: %1$s: %2$d/%3$d

>QUEST_FACTION_NEEDED
enGB: %s: %s / %s
deDE: %1$s: %2$s / %3$s

Will be taking a look at Spanish, French, Russian (or so I assume, because cyrillic), and Portuguese.

Then I'll be looking into making a workaround.

**Comment by daberniegithub** [comment]
Alright.
You need some german translations ? 
I am german.

**Comment by Aiue** [comment]
Oh yes, translators would be a very nice thing to have. Just need to make sure I have everything set up for it. I think using the wowace/curseforge localization tool should be viable, even with a github repo.

I'll look into it, then get back to this.

**Comment by Aiue** [comment]
I should have everything ready for localization now. Do you have a curseforge account?

**Comment by daberniegithub** [comment]
Yes but i do not find a way to enter translations in the german section.
Would you please double check if you allow translations from others.

**Comment by Aiue** [comment]
It's set to require me to grant permissions individually, which I would prefer. But I'll open it up for now.

**Comment by daberniegithub** [comment]
done...
I am not that experienced in translations but it should be a good 90% solution.
Some words make more sense to not translate them like "quests".
Some words I did not translate one 2 one because it would sound kind of bulky in german.
Some options i could not change ingame to check what exactly they do like "Intendation" but I think i guessed what they are for.
I would propose to give the first category under "General" a name so it is not displayed as "Uncategorized" which i correctly translated. Just use "General" again. 
For any questions or proposals for better translations feel free to contact me.

**Comment by Aiue** [comment]
Certainly! And thanks for the nice work. I'll to be better at providing context for translation keys in the future. And I do plan to move the Uncategorized section somewhere, hence the silly name. Just haven't figured out how to structure those particular options yet.

**Comment by Aiue** [comment]
Also adding a few more strings at the moment. Will probably be adding quite a bunch of them in the near future. Just to keep you on your toes!

Oh, and for "indentation", it's how far to inset subordinate lines from the margin. It's currently only a placeholder, I aim to have it functional soon.

But now, back to working on sorting configuration!
