### ISSUE TITLE
[Feature Request] Auto expanding and contracting

### ISSUE THREAD

**Issue by dalesnail** [Aiue/AQT#29]
A Feature to consider for the future might be automatically expanding quests for your current zone, and contracting those not in the zone. Should be doable as Carbonite does this well, but I prefer the tracker here to theirs.

**Comment by Aiue** [comment]
Should be very little work. I can probably get it done tonight.

**Comment by dalesnail** [comment]
Awesome! Looking forward to it.

**Comment by Aiue** [comment]
Seems to be working well. I just need to add an option to expand all. (Because it didn't seem to make sense to force expand all when toggling the setting to off.)

**Comment by Aiue** [comment]
Which means, leaving this open until I have done just that. Probably also a good idea to hold off on another release until at least that's been done.
