### ISSUE TITLE
Unable to see Quests 1.5 classic

### ISSUE THREAD

**Issue by Soultastic** [Aiue/AQT#31]
I don't know how or why, but since updating to 1.5 classic of the addon, none of the quests show in my tracker and it says 0/20 quests in my log. I had to roll back to a previous version.

**Comment by dalesnail** [comment]
Had this issue last night as well, thought it may have been related to #30, but maybe not.

**Comment by Aiue** [comment]
I've had no issues on my end, so I wouldn't know exactly how to reproduce the error. My guess is that it has something to do with getting faction information, but I can't know for certain without any lua errors.

If you could use [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber) and [BugSack](https://www.curseforge.com/wow/addons/bugsack) to catch the errors, that would be quite helpful. In the meanwhile, I'll look over the code again and try to come up with a safer way of doing things.

**Comment by Aiue** [comment]
Just pushed another update that I hope should fix this. Please let me know whether it did, or if the problem still persists.

Most likely it would be related to #30, at least, as that would halt the OnEnable() function before it registers any events.

**Comment by dalesnail** [comment]
Ok so mine is working fine now? Not sure why mine was not working previously, but I have had no issues tonight, so disregard my comment.

**Comment by Aiue** [comment]
I suspect the core of this issue is GetFactionInfo() having irregularities in how it will return on calls. It should be fixed, but as working with the WoW API is still down to quite a bit of guesswork, can't be certain.

I'll leave both tickets open for a few days, then if there have been no more reports of breakage, assume I have fixed the problem and close them.

**Comment by Soultastic** [comment]
It's working now with the latest. It must have been the faction thing. :)
