### ISSUE TITLE
[Style Feature Request] 2 Requests

### ISSUE THREAD

**Issue by dalesnail** [Aiue/AQT#32]
So I know that the style portion of the addon is a work in progress (oh and how much great progress you've made), but I was hoping to request 2 options. 

**1. Fading**

- I know this one is most likely on the list of features to be added, but I'm missing this dearly, as I use fading on the majority of my UI for immersion. Also a seperate option to toggle or fade the config cogwheel would be very nice.

 

**2. Keep aspect ratio of background textures option, and background zoom level option.** 
 - This one's a weird one I know, and it's halfway sort of niche, but this addon is perfect for theming the quest tracker. An example below of an instance where I would want this:

![2019-10-08 19_08_16-World of Warcraft](https://user-images.githubusercontent.com/20726565/66440494-2baaee00-ea01-11e9-9923-6f1a07ac9087.png)

![2019-10-08 19_09_00-World of Warcraft](https://user-images.githubusercontent.com/20726565/66440498-2fd70b80-ea01-11e9-95e4-ade5e646ae23.png)

Also just want to thank you for a wonderful addon!

**Comment by Aiue** [comment]
I have to admit, I had completely forgotten about the first one. I'm going to assume you mean alpha fading. It should be easy to fix, and something I can see myself prioritizing. Same with the cogwheel, as, to be honest, that one annoys me a bit too.

As for the other request, that will probably require a bit more rewriting, as, as far as I can tell, there is no way to do this when setting a backdrop for a frame. It's either stretch or tile. But as I'm writing this, I'm thinking that having an optional texture on top of the backdrop should be able to fix this.

Meaning, I should be able to do both tomorrow, with plenty of time to spare for working on other things. (I'll eat those words, I know.)

Yes, this type of style configuration intrigues me. I had actually not envisioned it being styled in such a way. You'll have to share the results once I've made the changes!

**Comment by dalesnail** [comment]
That's really great to hear! 

I'm always styling various UI stuff, so I always have weird ideas or niche ideas for customization haha.

**Comment by Aiue** [comment]
There, only the optional texture remaining. Just need to ponder the implementation a tiny bit, and see if I can get a tiny bit more feedback before going to work, since that could improve results.

I'm thinking about grouping it in the same tab as the backdrop (which needs cleanup, at least in my interface it looks somewhat jumbled
![image](https://user-images.githubusercontent.com/2452309/66482498-5f3e5480-eaa3-11e9-88b9-6391fa4489b8.png)
This just doesn't look good.

But apart from that, I'm thinking:
* One option to select a texture via LSM.
* One option to manually input the path to/id of the texture.
* Probably a button to unset it, although I think selecting "None" in LSM should accomplish the same, so can probably safely omit.
* A toggle for stretching. If stretching enabled - horizontal only, vertical only, or both.
* Where to anchor the texture, including offset.

Am I missing something?

**Comment by dalesnail** [comment]
I think all those options should work yeah, especially if the default is to keep the original aspect ratio. I would only add that a "zoom level" option would be nice. It's implimented in Weakaura icon textures, and I always seem to use it for things. 

Also a question, you mentioned that this would be on top of the backdrop, so would the 2 options have the ability to both be active? Could make for some interesting customization there as well, could do something like, have a pattern or art overlay, and change the background for class color. 

The None option would technically be the same, and most likely safe to omit yeah. Although I'll say, a visibility switch would be nice, similar to weakauras switch with the little eye. But that's definitely not necessary. 

I also have tons of other ideas for customization and features, but I dont want to feature creep you to death haha.

**Comment by Aiue** [comment]
Oh, I'm always hungry for more ideas on how to improve things.

As for zoom level, it seems the classic version of weakauras isn't packaged properly, so can't check it out right now. So just to get an idea of what kind of behaviour would be expected for that - are we simply talking size, or only showing partial texture? Because both should definitely be doable.

**Comment by Aiue** [comment]
Actually, since I'm pretty sure I can do both, I probably should do both. It's never a bad thing to give users the ability to customize things, as long as you don't create too much customization clutter.

**Comment by dalesnail** [comment]
So it would keep the size and dimensions of the original image, but when zoomed it would sort of "crop" it? I'll find an example and post below.....Actually made an example:

**_Unzoomed_**
![Unzoomed](https://user-images.githubusercontent.com/20726565/66487447-5422fe80-ea7a-11e9-82fa-e7b787b85359.png)

**_Zoomed_**
![zoomed](https://user-images.githubusercontent.com/20726565/66487455-58e7b280-ea7a-11e9-8eb5-f835a4a33900.png)

**Comment by dalesnail** [comment]
Also I'll post a few of my ideas for way's to make the project seem more polished, but I just don't want to overload you with requests. 

I'll do a small amount at a time haha.

**Comment by Aiue** [comment]
Just dropping by to update. Done about half the work now.  All the config options are done, just need to write the code doing the actual work. Aka the fun part.

Then test it to make sure it doesn't summon an army of leper gnomes or something silly like that.

But first, I need to kill some harpies.

**Comment by Aiue** [comment]
Well, that was kind of fun! May need some tweaking, but I think it should be able to do what you want it to do for the moment, at least!

**Comment by Aiue** [comment]
Felt cute, might tag a release later, idk.

**Comment by dalesnail** [comment]
_Ok so the extra texture option is amazing, and I have no clue why other addons don't do this now. Making innovations here right?!? hahaha_

_**Here's two I've made so far:**_

![image](https://user-images.githubusercontent.com/20726565/66525055-38434b00-eac2-11e9-921c-e558d8e0729b.png)

![image](https://user-images.githubusercontent.com/20726565/66525878-e0f2aa00-eac4-11e9-9e59-3a06924e2ae0.png)

![image](https://user-images.githubusercontent.com/20726565/66526006-3fb82380-eac5-11e9-8795-bb7fd1dac46f.png)


So this may not be possible, but I'm hoping it is. Is there a way to move the custom texture behind the border, but still over the backdrop? I think this option may be limited at least considering what you were saying about the backdrop issues previously. If that is possible, I think it would be necessary to have a swap back and forth there. 

Also on the **Fading**, would it be difficult to enable a timed automatic fade? Like it fades after 30 seconds with no interaction, and then comes back after mouse over? That was actually what I originally intended when asking. If this isn't possible, how about a full on minimize for the frame that moves the entire frame into one of these **------v**

![image](https://user-images.githubusercontent.com/20726565/66526098-886fdc80-eac5-11e9-80f4-009ac693cd46.png)

And one last thing for now, but I think for the custom texture options, the "Position" drop down, should be labeled as "Anchor" personally. I didn't realize that the option I chose was incorrect for one thing I tried, until I found it to be what I would normally associate with anchor functionality. 

**_Here's how I found out:_**

I had the position set to "Bottom Right" and then collapsed my quests, then this happened:
![image](https://user-images.githubusercontent.com/20726565/66526281-18ae2180-eac6-11e9-933a-41059aabdeab.png)

Honestly I could just be a big dumbass here lol, so this one is up to you! I did get it working by moving the anchor to the top.  

**:)**

**Comment by dalesnail** [comment]
Sorry for the GIANT comment

Also you should set up a paypal and a donation link. Would love to donate at some point!

**Comment by Aiue** [comment]
> So this may not be possible, but I'm hoping it is. Is there a way to move the custom texture behind the border, but still over the backdrop? I think this option may be limited at least considering what you were saying about the backdrop issues previously. If that is possible, I think it would be necessary to have a swap back and forth there.

Should be doable with some tinkering. Or at least I hope so. I'll keep it in mind for now, but will probably focus on other things at the moment.

> Also on the **Fading**, would it be difficult to enable a timed automatic fade? Like it fades after 30 seconds with no interaction, and then comes back after mouse over? That was actually what I originally intended when asking.

I would have to do some research before I can answer whether or not it would be difficult. It should certainly be doable, but I will probably slate that for after I'm done with the 1.1.0 milestone.

> And one last thing for now, but I think for the custom texture options, the "Position" drop down, should be labeled as "Anchor" personally. I didn't realize that the option I chose was incorrect for one thing I tried, until I found it to be what I would normally associate with anchor functionality.

Oh, I did just that. I probably should've gone with that from the start.

> Also you should set up a paypal and a donation link. Would love to donate at some point!

Well, if people want to throw money at me, I don't see any reason to turn them down, so there should now be a link in the readme.

Oh, also, would you mind if I stole some of those screenshots to share on the addon sites?

**Comment by dalesnail** [comment]
> Oh, also, would you mind if I stole some of those screenshots to share on the addon sites?

Let me get with the creator of the textures, and let them know. Should be good most likely, as we wouldn't be distributing the textures. 

I'll update when I hear back, and if for some reason it's a no, I can put together other themes to make the tracker look good for screenshots!

**Comment by dalesnail** [comment]
> >Also on the Fading, would it be difficult to enable a timed automatic fade? Like it fades after 30 seconds with no interaction, and then comes back after mouse over? That was actually what I originally intended when asking.

> I would have to do some research before I can answer whether or not it would be difficult. It should certainly be doable, but I will probably slate that for after I'm done with the 1.1.0 milestone.

Would you mind if I tinker with this? I'd like to learn lua at somepoint, and be able to make my own addons/contribute to others. If so, does this addon share a frame name with the default objective tracker? Think I at least have a lead here I'd like to try.

**Comment by Aiue** [comment]
> Would you mind if I tinker with this? I'd like to learn lua at somepoint, and be able to make my own addons/contribute to others.
Tinker all you want, I see no reason to take issue with that.
> If so, does this addon share a frame name with the default objective tracker? Think I at least have a lead here I'd like to try.
All frames have unique names, as the name is also the name of the global variable referencing them. AQT has one named frame, AQTParent and all childframes are nameless. But it seems reasonable that AQTParent is the one you'd want to tinker with for this purpose.

**Comment by dalesnail** [comment]
Got the go ahead to use any screenshots you need from mine. 

Let me retake one or two of them, because i just noticed that there is overlapping text in one.

**Comment by Aiue** [comment]
> Let me retake one or two of them, because i just noticed that there is overlapping text in one.

Oh yeah, I still need to look over why wordwrap is acting up.

**Comment by dalesnail** [comment]
![2019-10-10 18_11_53-World of Warcraft](https://user-images.githubusercontent.com/20726565/66610677-5eccb900-eb8a-11e9-8e09-16ae685e0622.png)
![2019-10-10 18_15_11-World of Warcraft](https://user-images.githubusercontent.com/20726565/66610679-60967c80-eb8a-11e9-958b-4ed4adfdfe2f.png)
![2019-10-10 18_15_46-World of Warcraft](https://user-images.githubusercontent.com/20726565/66610681-62604000-eb8a-11e9-9683-5777097b6a41.png)

**Comment by dalesnail** [comment]
Here's a few good ones for preview, may post one or 2 more

**Comment by dalesnail** [comment]
Last one, just threw one together that looked Blizzard like

![image](https://user-images.githubusercontent.com/20726565/66611177-adc71e00-eb8b-11e9-9516-507e53f97be5.png)
