### ISSUE TITLE
a few function suggestions

### ISSUE THREAD

**Issue by zwcol** [Aiue/AQT#39]
* click to open the questlog and show the details, and support some popular addons like Classic Quest Log, QuestLogEx etc

* drag to move the frame (on the tile or some handle)

* sound when a single objective is changed

* current zone highlight with bg color

* automatically fold non current zones

**Comment by Aiue** [comment]
> * click to open the questlog and show the details,

Planned. Looking at having an early version of this in by next week.
>  and support some popular addons like Classic Quest Log, QuestLogEx etc

Haven't tried those yet, but will take a look at it. But just for clarity, what do you envision this support would entail?
> * drag to move the frame (on the tile or some handle)

Planned. I'd put this at next week as well.
> * sound when a single objective is changed

I considered it, but then opted out of it. Then reconsidered it, then opted out of it again. I'l rereconsider it and put it in.
> * current zone highlight with bg color

Certainly doable.
> * automatically fold non current zones

Already in.  Check General/General/Headers: Automated Collapse/Expand.

**Comment by Aiue** [comment]
- [x] Clickable quests.
- [x] Support for other addons?
- [x] Unlockable frame for dragging.
- [X] Objective progress sound.
- [x] Highlight current zone.

**Comment by zwcol** [comment]
> and support some popular addons like Classic Quest Log, QuestLogEx etc

Here I mean if QuestLogEx is installed, and when we click the quest tracker, it can open the QuestLogEx frame instead of the built-in QuestLog frame.

Thanks for the response and great work on this addon!

**Comment by Aiue** [comment]
That makes sense, and assuming they have something occupying the global namespace that I can hook into, should certainly be doable.

I'll be out of time for the weekend, but will take a look at it once I get back home.

Meanwhile, I'll be pushing a few minor updates here that may or may not work. I expect I'll have a lot of code fixes to do when I get back home, but I guess such are the perils of coding on the train using an old netbook.

**Comment by Aiue** [comment]
I should also note that I have been planning on eventually writing my own questlog replacement to go with this. But support for other options is a good intermediary step that should be included regardless.

**Comment by zwcol** [comment]
> I should also note that I have been planning on eventually writing my own questlog replacement to go with this. But support for other options is a good intermediary step that should be included regardless.

Good to know that. And It might be better if users can choose from the addon's built-in questlog, blizzard default questlog or their other 3-party choices.

**Comment by Aiue** [comment]
I'll just add a note to myself here as well, since it's very much related to clickable quests: clicking the failure indicator should, if mouse is enabled, serve as a shortcut to abandoning the quest.

More shortcuts to consider would be using modified clicks to untrack (once manual tracking is in)/share, and potentially some other relevant thing.

And in case I write a retail version at some point, using the completion indicator as a shortcut for remote handins would be useful.

**Comment by zwcol** [comment]
Or you can consider leaving left-click to always open the questlog and using right-click to display a small context menu which provides other functions like untracking, abandoning, group sharing(if sharable), linking to wowhead, and etc?

And normally players use shift-left click to link things to the chats window when the text edit control is open. Do you have any plan to add such a function to this addon?

**Comment by Aiue** [comment]
Yes! I had even considered implementing my own way of linking quests. I'll have to do a tiny bit of research to see if it is at all viable, though.

A context menu makes sense as well, depending on the amount of options available, since modified click is limited to but a few options.

**Comment by Aiue** [comment]
Objective sound and current zone highligting is now fully functional. Dragging is behaving a bit.. strangely. Need to investigate a bit and adjust behaviour. The rest should be coming soon.

**Comment by zwcol** [comment]
Thanks for update. However the new version (downloaded from curseforge and overriding the installed addon folder), it gives errors:

![image](https://user-images.githubusercontent.com/56169239/66739541-d93a5900-ee68-11e9-9d6f-3f3ff8b2cc10.png)

**Comment by Aiue** [comment]
Well, that's embarrassing. I'll push a fix in a few minutes. Then I need to figure out why that behaves like that.

**Comment by Aiue** [comment]
There we go! If you happen across any other addons that it might make support, lemme know. I'll create a dedicated ticket for those. Closing this.
