### ISSUE TITLE
Error with an empty questlog

### ISSUE THREAD

**Issue by zwcol** [Aiue/AQT#40]
Happened on a new character:

```
2x AQT\Core.lua:169: table index is nil
AQT\Core.lua:169: in function <AQT\Core.lua:129>
AQT\Core.lua:190: in function <AQT\Core.lua:176>
[C]: ?
AQT\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <AQT\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
AQT\libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
AQT\libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <AQT\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:380: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:695: in function <FrameXML\UIParent.lua:658>
[C]: ?
```

**Comment by Aiue** [comment]
Spotted the error. I'll push a fix here, but coupled with my other changes, the current code may or may not be working properly. I'll have a release out fixing it by Sunday.

**Comment by Aiue** [comment]
Meanwhile, in Core.lua (not supplying file numbers now, though, since there may well be mismatches with my local copy):

in function factionInit():
`if not faction or faction == "Other" then
    if otherfound then`
should be
`if not faction or faction == "Other" then
   if not faction or otherfound then`

This should fix the issue.

**Comment by zwcol** [comment]
This problem seems to be a bit weird. The addon works well in my main character without any error reported, but when I created a new created character, it gives that error message and never goes away, even after I accepted a few quests in the questlog and did /reload. I noticed the config are saved per account and all profiles are set to Default:
```
AQTCFG = {
	["profileKeys"] = {
		["E**** - Pyrewood Village"] = "Default",   -- main character, works fine, human+mage
		["E****** - Pyrewood Village"] = "Default",  -- new character, error, human+warlock
		["B**** - Pyrewood Village"] = "Default",--  another new character, error, night elf+hunter
	},
	["global"] = {
		["hideCompletedObjectives"] = false,
		["hideQuestTimerFrame"] = false,

```
The version I'm using is AQT-1.0.7-classic downloaded from Cursefordge.

This is what the error looks like:-

![image](https://user-images.githubusercontent.com/56169239/66701626-09adb600-ecf6-11e9-8fd3-4ed63b0194e3.png)

**Comment by Aiue** [comment]
With this new information, I'm thinking I should rewrite the probably fix I already made. Make things a bit more foolproof. Although, it's strange if you have picked up quests, you should have spoked to NPCs initializing faction information, meaning it should be available. Unless it requires you to actually gain reputation before it being available.

Either way, I should be able to have a new release fixing this out by tomorrow night, European time. Until then, my response above should work as an intermediary measure.

**Comment by Aiue** [comment]
Reopening, didn't mean for the commit to close it just yet. :p

**Comment by Aiue** [comment]
Should be fixed in last release. Closing in a day or two if there are no reports of the problem persisting.

**Comment by zwcol** [comment]
Just to confirm that this problem has gone in the latest update (1.0.9-fix-classic). Thanks.
