### ISSUE TITLE
Increment Buttons

### ISSUE THREAD

**Issue by dalesnail** [Aiue/AQT#41]
Wonder if at some point we could add [+] and [-] increment buttons beside size and placement sliders in the config menus. It's just a bit difficult to make precise adjustments at times because of having to use the mouse.

**Comment by Aiue** [comment]
Those allow for manual input or numbers as well, no? The main issue with buttons would be figuring out how much each click would correspond to. Tuning by manually inputting a number instead is probably better for tuning purposes.

I could look into it, of course, but will probably opt out of it to avoid bloating the config too much. At least as long as I'm using AceConfig. Which perhaps I should reconsider. But that would be quite a bit later in that case.

**Comment by dalesnail** [comment]
You can manually type it in yeah, but a lot of times moving in small increments helps to know exactly what that number should be I guess. It's for sure a super minor thing though, so if this seems unnecessary to you all good :P

**Comment by dalesnail** [comment]
I'm gonna close this guy. Looking back on this one I realize that it would bloat the config a bit, and I wasn't aware of the limitations of AceConfig. I was contrasting options here with Details/Plater and Weakauras, which I think use way different libraries or something haha.
