### ISSUE TITLE
Y offset in layout is stuck at 2000

### ISSUE THREAD

**Issue by dalesnail** [Aiue/AQT#42]
Y offset in layout is set at 2000, and will not change back to anything else. Even tried to manually change in the lua file from WTF, but goes right back to 2000 when i reload, or touch the slider.

**Comment by Aiue** [comment]
Found it, Config.lua: line 845: `min = 2000,` should be `min = -2000`. I'll try having a release containing the fix out later today.

**Comment by dalesnail** [comment]
Thank you!

Will test this after work.
