### ISSUE TITLE
Suggestions on line display

### ISSUE THREAD

**Issue by zwcol** [Aiue/AQT#47]
- options to change the space between lines of zones/quests/objectives
- option to enable word wrap for long lines instead of truncation 
- options to customize leading characters to the objective line:
```
- Kobold Vermin slain                 0/10
* Kobold Vermin slain                 0/10
~ Kobold Vermin slain                 0/10
```

**Comment by Aiue** [comment]
The two former are things I have planned, but I've gotten sidetracked. Wordwrap behaves strangely, and I need to figure out why.

Leading character could be a nice alternative to indentation.

**Comment by Aiue** [comment]
May want to allow choosing any character, using an inputbox rather than dropdown with preset values.

**Comment by Aiue** [comment]
Still wordwrap and spacing to contend with. Need to take a look at how I handle resizing and give it a proper overhaul. Then figure out why wordwrap is being all kinds of wonky.

Basically the last few things I want to get done before making the 1.1.0 release.
