### ISSUE TITLE
 Settings -> General -> Sound

### ISSUE THREAD

**Issue by zwcol** [Aiue/AQT#49]
In this tab, when the `Use Faction Sound` option was unchecked, shouldn't be the sound dropdown list enabled?

And, the objective progress sound seems not being played.

![image](https://user-images.githubusercontent.com/56169239/67193373-195f8580-f3ed-11e9-8725-4e9bff6696f1.png)

**Comment by Aiue** [comment]
Hmm. Thought I had fixed that. Will investigate.

**Comment by Aiue** [comment]
Oooh. That's rather silly. I reversed the logic. Gonna need to head out and melt some faces to test the objective progress sound again.

**Comment by Aiue** [comment]
Ah, it seems it'll only play if faction sound is enabled. Looking into why.

**Comment by Aiue** [comment]
Seems to be working well now, will test the other sounds at various settings througout the day to make sure I didn't miss something.

**Comment by zwcol** [comment]
It appears to me that the sound for the last objective in "Objective Progress" is not functioning when "Objective Completion" is disabled:-

```
[16] Quest Title
- kill AAA      5/5
- kill BBB       6/6
```
when the 5th AAA is killed, there is no progress sound.

**Comment by Aiue** [comment]
Ah yes, I can see why it would do this. Will poke it later during the day.
