### ISSUE TITLE
Maximum width not updating frame

### ISSUE THREAD

**Issue by dalesnail** [Aiue/AQT#55]
Seems like only my minimum width is now updating frame width, with it staying as a static width. I'll try to post an example gif below: 

![MaxMinSliders](https://user-images.githubusercontent.com/20726565/67447909-6147fd80-f5e3-11e9-91c5-c2952620cfb5.gif)

**Comment by Aiue** [comment]
Seems to be working well on my end. In the example above, it does not have any reason to grow any wider, as no text is wrapped or truncated. It's only intended to go up to maximum width if any of the contents require it.

Wonder if I should go over the various configuration options and add tooltip descriptions for them. Probably a good idea for some of them, at least.

**Comment by dalesnail** [comment]
Ah fair enough, was definitely something i didn't think about when changing it, my fault. 

Tooltips are always a good help imo!
