### ISSUE TITLE
Request for modification of non-localized keys and suggestions for function

### ISSUE THREAD

**Issue by chkmyid** [Aiue/AQT#56]
non-localized phrase keys in AQT settings frame

1. General > Quest Tab > L["Hide Completed Objectives"] -- phrase key not found on curse.com
2. Mouse Interaction > L["Header"] Tab name -- phrase key not found on curse.com
3. Sorting > All Tabs names
  3-1. L["Header"] -- phrase key not found on curse.com
  3-2. L["Objective"] -- phrase key not found on curse.com
  3-3. L["Quest"] -- Need to apply to source code & phrase key applied to curse.com.
4. Sorting > All Tabs > L["Add new..."] of fields frame -- Need to apply to source code & phrase key applied to curse.com.
5. Style > General > L["Objective Prefix"] -- miss-string, "Objectives Prefix" phrase key applied to curse.com.
6. Style > Coloring > Highlight > L["Highlight Current Zone Text"] -- Need to apply to source code & phrase key applied to curse.com.
7. Style > Coloring > Highlight > L["Highlight Current Zone Background"] -- Need to apply to source code & phrase key applied to curse.com.
8. Style > Background > Artwork Texture > Drop down menu L["Full"] -- phrase key not found on curse.com

And can you help me print out the extract URL as "http://wow.inven.co.kr/dataninfo/wdb/edb_quest/detail.php?id=" for Korean users how the 'Get Wowhead URL' button works?
'wowhead.com' supports nine languages, but we would like to provide a 'phrase key' for the translator to localize.
For example,
The English URL is http://classic.wowhead.com/quest=
Chinese is http://cn.classic.wowhead.com/quest=
German is http://de.classic.wowhead.com/quest=
It's different from country to country.
By default, we would like to provide an English URL and other languages to be modified so that translators can include localized URLs.

Finally, the option's name should be modified to look truncated in the settings frame. In particular, the check buttons for 'Hide Completed Objectives' and 'Hide Objectives for Completed Quests' at the bottom of 'General-Quests Tab' will need to be aligned vertically.

Thanks!

**Comment by chkmyid** [comment]
L["Abandon Quest"] in Core.lua -- phrase key not found on curse.com
This key is not even found on the game screen.

**Comment by Aiue** [comment]
Can easily do the localized website links. I'll make sure to have it done by next release, but will retain the translation key. (Which means if it's translated to point to wowhead currently it should probably be changed before then.)

And I need to write a script to parse for any localization lookups. Should be a fairly simple matter, I'll get on it once I've wrestled with tracking automation a bit more.

And once all that's done, I'll take a look at polishing the configuration a bit.

**Comment by Aiue** [comment]
Links should now be localized. I think I'll push a release before beginning work on the parser.

**Comment by chkmyid** [comment]
I thought I'd simply change it to L["http://classic.wowhead.com/quest="].
I checked the code for complete modification. Thank you so much!

We will also look forward to seeing all keys that have not been localized. ;-)

**Comment by chkmyid** [comment]
Ah.. And there are reports of stop(or freezing?) when used with 'Questie' addon in Korea. I think we should use this together to identify the exact symptoms.

**Comment by Aiue** [comment]
That's something I'd like to fix. Not sure if it's on my end or theirs. Will need to investigate. Any idea in which situations the freeze occurs?

**Comment by Aiue** [comment]
There, parsed and, err, parsed my parse. Any missing keys should now be added on curseforge.

Need to see if I can fully automate this.

**Comment by chkmyid** [comment]
The conflict with 'Questie' was that only two addons were used while the quest list was full and all other addons were disabled for testing. The symptom is that the screen freezes as soon as the computer is racking up during the game.

**Comment by Aiue** [comment]
Righto, I'll see if I can reproduce it and figure out what's causing it.

**Comment by chkmyid** [comment]
Marked part not yet localized. Please check again.

![WoWScrnShot_1](https://user-images.githubusercontent.com/55096941/67613498-3af3af00-f7e9-11e9-919f-325f3993593b.jpg)
![WoWScrnShot_2](https://user-images.githubusercontent.com/55096941/67613499-3af3af00-f7e9-11e9-9d06-164d752861c0.jpg)
![WoWScrnShot_3](https://user-images.githubusercontent.com/55096941/67613500-3b8c4580-f7e9-11e9-9aad-189ac2a24d9d.jpg)
Adjust the empty space at the bottom so that the text is not cut off.

**Comment by Aiue** [comment]
Ah, yes, I had a slightly different scheme for how I looked up those localization keys. Which means the parser would miss them. I'll make sure they get captured properly and set them in the localization system. I will also make that configuration option wider.

I've been unable to reproduce the issue with Questie, but I'll see if I can find something in the code that looks like it could cause an issue.

**Comment by Aiue** [comment]
Actually, "Quest" should translate properly, as that key exists. I'm gonna have to do some testing here.

**Comment by Aiue** [comment]
Ah, yes, the sorting doesn't even do localization lookups. Will fix. Also adding proper localization lookups do zone highlighting.
