### ISSUE TITLE
A problem in which mouse interaction is not working.

### ISSUE THREAD

**Issue by chkmyid** [Aiue/AQT#58]
A problem in which mouse interaction does not work due to an irregularly generated highlight background when the mouse is over the quest header.

![WoWScrnShot_1](https://user-images.githubusercontent.com/55096941/67630938-6acab180-f8d2-11e9-924f-b515a3bbaf79.jpg)

The left side of the screen shot above is the background of the highlight that is only able to operate normally when the mouse is over carefully. However, under normal circumstances, mouse interaction cannot work no matter how hard you try if the mouseover is displayed as the highlighted background shown in the screenshot on the right.
If you take a closer look at the screenshot, you can see that the poor highlighting background is higher.

![WoWScrnShot_2](https://user-images.githubusercontent.com/55096941/67630985-268be100-f8d3-11e9-960f-4d8924cfe4af.jpg)
![WoWScrnShot_3](https://user-images.githubusercontent.com/55096941/67630987-28ee3b00-f8d3-11e9-8d24-a24f39a461c5.jpg)

Highlighting backgrounds that make mouse interaction impossible are sometimes found between performance objectives.

**Comment by Aiue** [comment]
I have not been able to replicate this myself, and wonder if it is somehow locale-specific for some odd reason. I will try to investigate it, but without being able to generate the error myself, I'm not sure where to begin.

I'll make it a point to switch to the Korean locale to do some additional testing soon.

**Comment by Aiue** [comment]
![image](https://user-images.githubusercontent.com/2452309/67708039-d177ca00-f9bb-11e9-8d97-d0466c553fc4.png)
I have no clue what it says, but it appears I will not be able to login with locale set to Korean to test things. Sad.

**Comment by chkmyid** [comment]
A pop-up window shows you that you have connected to a server whose language does not match.

I think you can connect to the Korean server.

**Comment by chkmyid** [comment]
Step 1. Create Account
![step1](https://user-images.githubusercontent.com/55096941/67728410-8055ed80-fa30-11e9-8a96-dbd5e67ecbc0.png)
![step2](https://user-images.githubusercontent.com/55096941/67728459-aaa7ab00-fa30-11e9-90cd-1c50d9ca2be5.png)
![step1-1](https://user-images.githubusercontent.com/55096941/67728481-b85d3080-fa30-11e9-8bbe-da63a96b1d19.png)
![step1-2](https://user-images.githubusercontent.com/55096941/67728482-bb582100-fa30-11e9-8c2b-be1245f3743a.png)

Step 2. Buy 'Game time'
![step3](https://user-images.githubusercontent.com/55096941/67728493-c448f280-fa30-11e9-8f96-9a25b7922289.png)
![step4](https://user-images.githubusercontent.com/55096941/67728497-c612b600-fa30-11e9-9ddd-485aad1a6a34.png)
![step5](https://user-images.githubusercontent.com/55096941/67728498-c743e300-fa30-11e9-86ab-ec4b7c0b92d8.png)

Step 3. Play game.

Note: To access realm servers in other countries, you need to purchase account game time for that country.

**Comment by Aiue** [comment]
Yeah, I figured it'd be something of the sort. Not overly keen on throwing more money at Blizzard for the sake of being able to figure out what kind of inconsistencies they have in their API between various locales. The principle of the thing is kind of appalling.

I'll start off with seeing if I can talk Blizzard into giving me access to the proper testing environment. Not that I'm expecting much on that end.

**Comment by Aiue** [comment]
![image](https://user-images.githubusercontent.com/2452309/68172773-18942b00-ff79-11e9-90ea-e8f98142475d.png)
So for now my only recourse is to lobby Blizzard to allow access to realms regardless of locale settings, or have their devs take steps to ensure there are no inconsistencies between locales.

**Comment by chkmyid** [comment]
Blizzard's insincere reply is back.
In my experience, this problem is not yet occurring again after the patch.
I think closed to the issue.

**Comment by Aiue** [comment]
Alright! Well, hopefully I can still make it happen in case any future problems would occur. :p
