### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by dalesnail** [Aiue/AQT#61]
Might be a little much at this time, but would be nice to interact in real time for small things that maybe don't require a full bug report.

**Comment by Aiue** [comment]
I'll take a look at this ..eventually. :p

Another bonus of discord would be that I would be able to hook it into my current automation, and have it announce new releases, and with some tweaks, new localization strings.

**Comment by Aiue** [comment]
Created a [discord](https://discord.gg/tYxQ7Bm). Gonna need a bunch of reconfiguring later on. But it's a start. Should currently at least have automation set up to announce new localization system entries on it, woop!

**Comment by Aiue** [comment]
![image](https://user-images.githubusercontent.com/2452309/67740137-15e38400-fa15-11e9-9ff8-813b8bb5fdc2.png)
Glee
