### ISSUE TITLE
I think 'Lighten' and 'Darken' options are the opposite.

### ISSUE THREAD

**Issue by chkmyid** [Aiue/AQT#66]
What do you think?

**Comment by Aiue** [comment]
Should only be the opposite if you set the modifier to a negative value.  Which is basically what the "Darken" function does. It just calls the Lighten function with the negative modifier value. (Or was it the other way around?)

Testing it right now, and darken turns my strings darker, while ligten does nothing (as they can't get any brighter.  ... maybe that should've actually been named "brighten")

**Comment by Aiue** [comment]
![image](https://user-images.githubusercontent.com/2452309/68000501-a9f55b80-fc60-11e9-9f6c-f872782e7c1a.png)
This is using "Darken".

**Comment by Aiue** [comment]
I'm curious, though. With background highlight turned off, does the thing where entries become unclickable still occur?

**Comment by chkmyid** [comment]
I thought the dropdown menu was a template option.
If you set the modifier to zero percent, it doesn't work.
Don't you need a dropdown menu? Because it is operated by the "Modifier" function.

Background highlighting is not a problem yet.
