### ISSUE TITLE
Quest Description in Tooltip on Mouseover

### ISSUE THREAD

**Issue by dalesnail** [Aiue/AQT#70]
**Quest Description in tooltip on mouseover:**

- Potential option to enable only with modifier key, in case someone only wants it sometimes. i.e. I mouse over a quest header, hold alt, then the description shows. 
- Potential customization with this to truncate after a specified number of lines, or to show all. 

_Thought I would post here after talking in discord_

**Comment by Aiue** [comment]
Aye, been working a bit on it. Gonna make it very similar to how click-commands work. Very, very similar.

Most of the underlying code is in already. All that remains is setting up the config options and writing the functions that would add quest information to the tooltip.
