### ISSUE TITLE
Click to open QuestLogEx

### ISSUE THREAD

**Issue by zwcol** [Aiue/AQT#71]
It happens to me that the opened QuestLogEx is not automatically located at the clicked quest but always shows the first quest. I can't remember since when this problem started but previously this function worked perfectly.

Thanks.

**Comment by Aiue** [comment]
As far as I can tell, QuestLogEx is a beta version that is not actively developed. While this is the case, chances are that I will not actively maintain support for it.

I might look into taking steps to ensure some basic functionality soonish, though.
