### ISSUE TITLE
An error message occurs when you click on the "Header" tab of the category "Mouse Interaction".

### ISSUE THREAD

**Issue by chkmyid** [Aiue/AQT#72]
3x AQT\Config.lua:467: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
AQT\Config.lua:467: in function `member'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-78.lua:221: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:169>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-78.lua:1235: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-78.lua:1144: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-78.lua:1648: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-78.lua:1573: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1557>
[C]: ?
...aceBartender4\libs\AceGUI-3.0\AceGUI-3.0-40.lua:72: in function <...aceBartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:70>
...aceBartender4\libs\AceGUI-3.0\AceGUI-3.0-40.lua:290: in function `Fire'
...libs\AceGUI-3.0-40\widgets\AceGUIContainer-TabGroup.lua:156: in function `SelectTab'
...libs\AceGUI-3.0-40\widgets\AceGUIContainer-TabGroup.lua:67: in function <...libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:64>

**Comment by chkmyid** [comment]
This error message will continue to increase while the config frame is open.

**Comment by Aiue** [comment]
Yeah, I forgot to take into account that some object types can have click interaction without having any tooltip scripts. I'll push a fix in a bit.
