### ISSUE TITLE
Suggestion : Show quest tags by quest type

### ISSUE THREAD

**Issue by chkmyid** [Aiue/AQT#79]
In the Korean client, next to the quest level, the quest type is displayed as "?" for dungeon, elite, raid, and legendary quest.

> [52?] Quest title

I would like to add the customize option so that users can specify by quest type.

Alternatively,

Elite quests and Dungeon quests = "+"
Raid quests and Legendary quests = "++"

or

Dungeon quests = "D",
Elite quests = "+",
Raid quests = "R",
Legendary quests = "++",

which work with other trackers.
What do you think of this?

**Comment by Aiue** [comment]
Oh. This is probably why SendChatMessage failed as well. The lua string library probably can't handle utf8 well.

I'll see if I can compare the tag against global strings and provide special handling for clients not primarily using the latin alphabet.

**Comment by Aiue** [comment]
I'll make sure to tag a commit including this change later today, I'll just give it a wee bit of time to see if there's anything else I'll want to include first.

**Comment by chkmyid** [comment]
These issues are the same for Korean(koKR), Chinese(zhCN, zhTW) and Russian(ruRU) clients.

**Comment by Aiue** [comment]
I suspected as much. I'm going to push a tag with the fix, and leave this open for now, as a reminder to myself that [`	 countertext = have:sub(1,1) .. "/" .. need:sub(1,1)`](https://github.com/Aiue/AQT/blob/db908c2316393c18df9e8874ab663f65427f49be/Core.lua#L615) needs to be fixed as well.

**Comment by chkmyid** [comment]
I didn't do enough testing because it was time to go to sleep. But if I check it out for a moment, it's normal.

![WoWScrnShot_1](https://user-images.githubusercontent.com/55096941/68782315-8973cb00-067c-11ea-833f-604722cad20a.jpg)

**Comment by Aiue** [comment]
Forgot to mention the issue, but https://github.com/Aiue/AQT/commit/cb7fb16ccbfeb6d205c223103d537f5e8d19979b closes this.
