### ISSUE TITLE
Error when clicking quest in tracker to open log

### ISSUE THREAD

**Issue by Nuroduas** [Aiue/AQT#84]
I am getting similar errors using either Wide Quest Log or BEQL for a 2 panel quest log.  When clicking quests in the tracker they generate and error based on the Quest Title returning NIL.  I have done a few test and in all cases when I disable AQT the errors go away.

Date: 2019-12-07 10:46:14
ID: 1
Error occured in: Global
Count: 8
Message: ..\AddOns\beql\questlog.lua line 384:
   attempt to concatenate local 'text' (a nil value)
Debug:
   beql\questlog.lua:384:
      beql\questlog.lua:371
   [C]: SetText()
   AQT\QLU.lua:55: QuestLog_Update()
   AQT\Core.lua:293: func()
   AQT\GUI.lua:1202:
      AQT\GUI.lua:1120
Locals:
self = QuestLogTitle1 {
 0 = <userdata>
 hookCall = true
 highlight = QuestLogTitle1Highlight {
 }
 r = 0.700000
 Text = QuestLogTitle1NormalText {
 }
 g = 0.700000
 _OnClick = <function> defined *:OnClick:1
 groupMates = QuestLogTitle1GroupMates {
 }
 normalText = QuestLogTitle1NormalText {
 }
 b = 0.700000
 check = QuestLogTitle1Check {
 }
 isHeader = true
 SetText = <function> defined =[C]:-1
 tag = QuestLogTitle1Tag {
 }
}
button = QuestLogTitle1 {
 0 = <userdata>
 hookCall = true
 highlight = QuestLogTitle1Highlight {
 }
 r = 0.700000
 Text = QuestLogTitle1NormalText {
 }
 g = 0.700000
 _OnClick = <function> defined *:OnClick:1
 groupMates = QuestLogTitle1GroupMates {
 }
 normalText = QuestLogTitle1NormalText {
 }
 b = 0.700000
 check = QuestLogTitle1Check {
 }
 isHeader = true
 SetText = <function> defined =[C]:-1
 tag = QuestLogTitle1Tag {
 }
}
questIndex = -7
spacing = "  "
text = nil
tag = ""
(*temporary) = "  "
(*temporary) = ""
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to concatenate local 'text' (a nil value)"
beql = <table> {
 QuestWatchAnchor_OnUpdate = <function> defined @Interface\AddOns\beql\questtracker.lua:233
 modules = <table> {
 }
 TileButtonOnClick = <function> defined @Interface\AddOns\beql\questlog.lua:355
 SecureHook = <function> defined @Interface\AddOns\beql\Libs\AceHook-3.0\AceHook-3.0.lua:336
 FadeColors = <function> defined @Interface\AddOns\beql\beql.lua:297
 QuestTracker_ScheduleUpdate = <function> defined @Interface\AddOns\beql\questtracker.lua:228
 OpenBlizzardOption = <function> defined @Interface\AddOns\beql\options.lua:1337
 autoWatchQuestProgress = <function> defined @Interface\AddOns\beql\questtracker.lua:68
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\AQT\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 TileButtonSetText = <function> defined @Interface\AddOns\beql\questlog.lua:371
 AddFrameScripts = <function> defined @Interface\AddOns\beql\beql.lua:431
 watchFrameLine_OnMouseDown = <function> defined @Interface\AddOns\beql\questtracker.lua:674
 IsEnabled = <function> defined @Interface\AddOns\AQT\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 decToHex = <function> defined @Interface\AddOns\beql\beql.lua:319
 GetQuestLogTitle = <function> defined @Interface\AddOns\beql\quest.lua:299
 GetQuestTimer = <function> defined @Interface\AddOns\beql\quest.lua:378
 callbacks = <table> {
 }
 UnregisterMessage = <function> defined @Interface\AddOns\AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 initQuestLogTitleButton = <function> defined @Interface\AddOns\beql\questlog.lua:294
 hooks = <table> {
 }
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\AQT\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 questWatchRemoveQuest = <function> defined @Interface\AddOns\beql\questtracker.lua:85
 questLogAnchor_OnEvent = <function> defined @Interface\AddOns\beql\beql.lua:141
 OnEnable = <function> defined @Interface\AddOns\beql\beql.lua:104
 Compatibility = <function> defined @Interface\AddOns\beql\options.lua:1348
 Tooltip_InitTooltip = <function> defined @Interface\AddOns\beql\tooltip.lua:43
 watchFrameLine_OnEnter = <function> defined @Interface\AddOns\beql\questtracker.lua:646
 OnInitialize = <function> defined @Interface\AddOns\beql\beql.lua:67
 NewModule = <function> defined @Interface\AddOns\AQT\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 questCache = <table> {
 }
 debugprint = <function> defined @Interface\AddOns\beql\beql.lua:50
 round = <function> defined @Interface\AddOns\beql\beql.lua:395
 QuestLog_ExtendedQuestLog = <function> defined @Interface\AddOns\beql\questlog.lua:159
 watchFrame_OnDragStart = <function> defined @Interface\AddOns\beql\questtracker.lua:633
 revision = "1.1.1 Alpha 3"
 On = <function> defined @Interface\AddOns\AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 Hooks_GameTooltip_OnTooltipSetUnit = <function> defined @Interface\AddOns\beql\tooltip.lua:92
 restoreLayout = <function> defined @Interface\AddOns\beql\questlog.lua:444
 name = "beql"
 initChat = <function> defined @Interface\AddOns\beql\chat.lua:10
 Disable = 
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AQT, v1.1.8-r2
  Atlas, vv1.45.01.11302
  AtlasBattlegrounds, vv1.45.00.11302.00
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasTransportation, vv1.45.00.11302.00
  AtlasLootClassic, vv1.4.1
  AtlasLootClassicData, vv1.4.1
  AtlasLootClassicDungeonsAndRaids, vv1.4.1
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BagnonScrap, v8.2.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  beql, v1.1.1 Alpha 3
  Chinchilla, vv2.10.0
  DBMCore, v1.13.23
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Dominos, v8.2.30
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FishingBuddy, v0.7 Beta 1
  GatherMate2, v1.45.5
  GrimoireKeeper, v1.2
  HandyNotes, vv1.5.9
  HandyNotesDungeonLocationsClassic, v1.03
  HandyNotesFlightMastersClassic, v1.06
  HandyNotesNPCsClassic, v1.21
  HandyNotesTravelGuideClassic, vv2.1.6
  HandyNotesWorldMapButton, v11302.02-Classic
  Healium, v
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  Mapster, v1.8.5
  MoveToolTip, v1.0.6
  OmniCC, v8.2.5
  Questie, v5.2.3
  RealMobHealth, v2.13
  Scrap, v13.19
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpinxFocus, v1.0
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TrackingEye, v1.1.1
  ZoneDetails, v1.0.1
  ZPerl, v5.8.8
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=84c)

**Comment by Aiue** [comment]
> questIndex = -7

This seems to be why. I'll look into what might be causing that. Also, apologies for the lengthy absence.

**Comment by Nuroduas** [comment]
I'll test and see what I get

**Comment by Nuroduas** [comment]
Not getting error but still not working correctly.  I think I know how to reproduce it specifically in the previous version and current update.  

Two things are happening:
If I am using the standard quest log (no mod) and click the last quest in the Log or the last quest in the AQT Tracker from the tracker I get an empty quest log.  If I click any other quest form the Tracker the quest log is fine.  Side note that while the log is empty when clicking the last quest of the log or last of the tracker the default quest log has a scroll bar and if I scroll the log appears.

Using BEQL quest log I get a slightly different outcome.  Only clicking the last log of the quest shows no quest log.  BEQL shows not scroll bar.  Closing and reopening or clicking any other quest in tracker shows the log correctly.

In both cases the Quest Detail shows correctly just the Log that is empty.

I'm not sure you have debug settings to trace this but if you do I'd be happy to experiment and help.
